apiVersion: skupper.io/v2alpha1
kind: AccessToken
metadata:
  name: clustera-a11301f8-9864-438b-8524-539fd48c3f20
spec:
  ca: |
    -----BEGIN CERTIFICATE-----
    MIIDNzCCAh+gAwIBAgIRAIObcTR8mIEmBO4hopqD9UowDQYJKoZIhvcNAQELBQAw
    HzEdMBsGA1UEAxMUU2t1cHBlckdyYW50U2VydmVyQ0EwHhcNMjUwODAxMjMxMDA4
    WhcNMzAwNzMxMjMxMDA4WjAfMR0wGwYDVQQDExRTa3VwcGVyR3JhbnRTZXJ2ZXJD
    QTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALMJMLL8NUuncOkuOAhC
    euej25iZHxpyWgCFWyK1u7+7x370JeO7YnxQd8ei/Afy2OeqyuaCeZx8mJi0INVI
    QGhi3X80Y0PigZw9E358Vg5Kj4LVYQKvApn++skAQuI0YYHOEXGkbNCzo/Jopphg
    4qUdNkpnFxAS9COy7Cex43KmpLOYTHfn5nUYfmeM5zjrASteNXOxNwE8Ec6cwX7x
    f3O+BqOuxTvsnrdIgmli8KwsUxqiipjkTTD7tc/f/TaRStiCuzNGrUVqNtjQLag1
    fcNis4cxLKQLrN1ThCYZzilKGUvP0JZgCA1NlXUu+Chq+VC5enV4muGlwdG65Rzd
    zqMCAwEAAaNuMGwwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRrJYNI0J/PSbTS
    ti4q0RQhv0m7kDALBgNVHREEBDACggAwDQYJKoZIhvcNAQELBQADggEBAFGXQbpn
    YKx3gWCTqsaL8FOQTtRjz8u7Px05PpEg5jKnItJ1SI+cDr6fW7QZimpuGXn7aUO2
    GcWDjQfor/Mja26sSkfe2HAYprMQ70YGXSy/3MKC+QqzG/vkgWceVQR25i+yLEG3
    WoNhvl72vVX68+bbe1NxLXtOtN4anZdbyaLs6sf+2EJffWbXivMGy+zl04v64Frg
    O3NKY/r8tEi2CTWofxe7W1OYbs1O+2gUIwRqgcq2rvukVnZKG9QrpSod3e10iqJP
    1E9jDAIU4eZ+HWE7agBN1N/6GHNx9BdbRm/qtSnPdfjHbAxdOY2WkA4Nd7r35hwT
    xyBJRiWGpRbwtNI=
    -----END CERTIFICATE-----
  code: 5Av2mBF010JWi03fLHZ9eoef
  linkCost: 1
  url: https://skupper-grant-server-https-openshift-operators.apps.clustera.goguybrush.com:443/6ccb22e7-eb44-45f6-a66c-0c1f9ceb5224
